name: Build and Release Electron App

on:
  push:
    branches: [ Stable ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            set ELECTRON=true && npm run build
          else
            ELECTRON=true npm run build
          fi

      - name: Package Electron app
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            npx electron-builder --win --x64 --arm64 --config.extraMetadata.main=electron-main.cjs
          else
            npx electron-builder --mac --x64 --arm64 --config.extraMetadata.main=electron-main.cjs
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Stable'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist-artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
